import type { Metadata } from "next";


import "./globals.css";

import "@fontsource-variable/nunito-sans";

import "@fontsource-variable/rubik";
import "@fontsource/jomhuria";
import "@fontsource/poppins";
import AppContainer from "@/components/AppContainer";
import { Toaster, toast } from "sonner";



export const metadata: Metadata = {
  title: "Stackbuld E-commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Toaster richColors />
        <AppContainer>{children}</AppContainer>
      </body>
    </html>
  );
}
